added calculation of tank mass for verification
aesirkth/propulsion-simulations pull request #2
Opened 2020-03-22 13:11 UTC by RandomeName745

2020-03-22 14:02 UTC, eweilow requested changes
Nice 👍 left some thoughts

2020-03-22 14:02 UTC, eweilow commented on rocket3/flightStudy/setup/capsuleTank.m
> +    m = 2 * pi * R.^2 .* (R + L) * P * rhoOverSigma * s;
Perhaps `s`could be changed to `safetyMargin` or similar - since that appear to be the usage of it?

2020-03-22 14:02 UTC, eweilow commented on rocket3/flightStudy/setup/computeDerivedFlightOpts.m
> +    [ccMass, ccLength, ccWallThickness] = capsuleTank(opts.FuelVolume, 0.075, combustionPressure, 1.35e-5, 200*10^6, 2700, 1.5);
Maybe the safety margin can be extracted into an `opts.PressureVesselSafetyMargin` or similar? 👍 

Actually, perhaps all of these assumptions should be placed into `opts` with reasonable names?

2020-03-22 14:02 UTC, eweilow commented on rocket3/flightStudy/setup/computeDerivedFlightOpts.m
> +    opts.OxidizerTankWallThickness = oxTankWallThickness;
Perhaps add `opts.CombustionChamberWallThickness` too?

2020-03-22 14:02 UTC, eweilow commented on rocket3/flightStudy/setup/capsuleTank.m
> +    m_check = t_check .* (2*pi * R * rho * (2*R + L));
`t_check` and `m_check` are not used here from what it looks like, perhaps add them as return values from this function? 👍

2020-03-22 14:02 UTC, eweilow commented on rocket3/flightStudy/setup/computeDerivedFlightOpts.m
> +    [ccMass, ccLength, ccWallThickness] = capsuleTank(opts.FuelVolume, 0.075, combustionPressure, 1.35e-5, 200*10^6, 2700, 1.5);
Also realized that the radius probably should change with the rocket radius (but this was not the case before this PR either)

2020-03-22 14:02 UTC, eweilow commented on rocket3/flightStudy/setup/capsuleTank.m
> +    m = 2 * pi * R.^2 .* (R + L) * P * rhoOverSigma * s;
Maybe it's nice to remove rhoOverSigma now that we pass both Sigma and rho to the function

2020-03-22 18:35 UTC, RandomeName745 commented on rocket3/flightStudy/setup/capsuleTank.m
> +    m = 2 * pi * R.^2 .* (R + L) * P * rhoOverSigma * s;
Yes, good points. We should also check the values again

2020-03-22 20:28 UTC, RandomeName745 commented
Hey, I made the changes. I also updated the material properties according to a data sheet. Thats not fixed however. Where did you get the value of rhoOverSigma = 1.35e-5 which was used before? This would mean that the allowable stress (sigma) is 200 N/mm2. I didnt find values for the allowable stress but assumed it to be half of the yield strength for now.

Another comment from me: What do you think about outsourcing all the definition like material properties which are defined at the beginning of computeDerivedFlightOpts.m? Makes the code a bit tidier. I used .txt files in previous projects for this. So you edit the values there and load it in the function.

2020-03-22 21:45 UTC, eweilow commented on rocket3/flightStudy/setup/computeDerivedFlightOpts.m
>      opts.CombustionChamberMassIsh = ccMass;
Hahaha `MassIsh` 🤣 
Nice 👍

2020-03-22 21:47 UTC, eweilow approved these changes

2020-03-22 22:00 UTC, eweilow commented
Nice, I say we can do further changes at a later stage

2020-03-23 17:29 UTC, RandomeName745 commented
So now I outsourced the parameters. What do you think of that?

Maybe we should also remove the hard coded 'engineMass = 6;' in computeDerivedFlightOpts.m and predefine it in assumptions or something similar?

If you are ok with that, I think you can merge the files :)

2020-03-23 17:53 UTC, eweilow commented on rocket3/flightStudy/setup/capsuleTank_data_input.m
> +ofRatio = 4;
Perhaps the oxidizer fuel ratio shouldn't be in this file

2020-03-29 10:05 UTC, merged